### ISSUE TITLE
Should prt itself have the capability to glob? [discussion, enhancement]

### ISSUE THREAD

**Issue by cxw42** [hitode909/App-PRT#37]
This relates to https://github.com/hitode909/App-PRT/blob/master/lib/App/PRT/CLI.pm#L72-L75 .  In my testing,

    $ prt list_files 'lib/**/*.pm'
    lib/**/*.pm does not exist at lib/App/PRT/Collector/Files.pm line 17.

However,

    shopt -s globstar; prt list_files lib/**/*.pm

works fine, because the shell expands the wildcards.

Should prt itself be able to expand wildcards?  In https://github.com/hitode909/App-PRT/pull/36#issuecomment-496751630 , @hitode909 mentioned 

> `File::Zglob` may resolve the glob issue. I'll try this module later.
> - https://metacpan.org/pod/File::Zglob

I know there is also https://metacpan.org/pod/File::Globstar .

**Comment by hitode909** [comment]
git seems expand the wildcards.

```
bash-5.0$ git grep package lib/**/*.pm | wc -l
       1
bash-5.0$ git grep package 'lib/**/*.pm' | wc -l
      36
bash-5.0$ shopt -s globstar; git grep package 'lib/**/*.pm' | wc -l
      36
bash-5.0$ shopt -s globstar; git grep package lib/**/*.pm | wc -l
      36
```

**Comment by cxw42** [comment]
Thanks for finding those links!  Yes, I only learned recently that git will glob.  For example, to reset the working directory, I can say `git checkout -- '*'` and not have to list all the filenames :) .

I personally have not yet needed prt to glob, but it would be useful on Windows since cmd doesn't have globstar.  What do you think?  YAGNI, or a feature that would prove its worth over time?

**Comment by hitode909** [comment]
> YAGNI

I think so too, let's reopen this issue when someone wants this feature!
